### ISSUE TITLE
Refactor Applogic in App.js

### ISSUE THREAD

**Issue by jwhittle933** [jwosborn/Adapter-app#1]
Suggestion for conditional rendering on line 15 in App.js

Instead of current:
```
class App extends Component {

  render() {

const Applogic = () => {
  const hasHDMI = true; 
  if (hasHDMI) {
      return (<Positive />)
    } return (<Negative />)

}
    return (
      <div className="App">
        <Header />
        <Select 
        opts={Nortonlist}
        dopts={Devicelist}
        />
        <Applogic />
      </div>
    );
  }
}
```
I would do this: 
```
class App extends Component {
  state = {
     hasHDMI: true
  }
 render() {
    return (
      <div className="App">
        <Header />
        <Select 
        opts={Nortonlist}
        dopts={Devicelist}
        />
        {
            this.state.hasHDMI ? <Positive /> : <Negative />
        }
      </div>
    );
  }
}
```
This uses dynamic rendering and is a much more React way of doing things. Now you only have to wire up the way to determine the truthiness or falsiness of hasHDMI and React will re-render based on the change. 

Also, don't declare stateless functional components (i.e., Applogic) within a React class component. You have it declared within the render() block of the App component, which I believe you _technically_ you can do but...__don't__. This component has nothing to do with App and should be declared in a separate module or above the App class.

**Comment by jwosborn** [comment]
hasHDMI was a placeholder just to test the conditional so I def don’t want it in state. Love the ternary syntax though. Gonna use it. Never think of it bc I'm not super familiar with it. 

The reason I had Applogic in the app component was bc, in my mind, it is the main logic in the entire app. That conditional statement is basically the code version of “do i need an adapter?” What you said makes sense though. Should I make it it's own component even though it will just be a large function once I've finished it without any rendering?

**Comment by jwosborn** [comment]
What if I create a variable needsAdapter that gets changed from true to false depending on the matching of the nortonList and deviceList arrays. Then that variable gets plugged into the ternary expression you wrote.

**Comment by jwhittle933** [comment]
It depends on how you want to determine if the user has hdmi or vga (or usb c, don't the way Apple screwed us all). The state here is simply a place for your App to know something for conditional rendering. You don't need to create _central logic_ within the App component. Technically, the App component *__is__* the central logic, especially when your application is so small. 

I would write a function that handles the selections that are chosen from the UI and uses them to set the Application state, then dynamically render based on that. 

Also, (here's)[https://guides.github.com/features/mastering-markdown/] a github markdown cheatsheet, for formatting text in these comments  and in your README.md files.

**Comment by jwosborn** [comment]
The only ways to connect to our systems are HDMI and VGA. USB-C does not need to be an option, but will be an "adapter" key that I haven't added into the data object on Devicelist. I'm not concerned with editing data until I get the app to work as I intend. 

When I would try to place the conditional directly within App.js it didn't like it, but I think it's bc I was trying to ping an "else" keyword which is not necessary in React. That's why I ended up moving it out of the return statement. Makes much more sense to use the ternary in the return and place needsAdapter in state and manipulate it from the function that matches the UI input. 

Thanks for that guide. I'll try to familiarize myself with it in the next few days.
