### ISSUE TITLE
Questions about targetValue

### ISSUE THREAD

**Issue by jwosborn** [jwosborn/Adapter-app#2]
I currently have a function called targetValue that simply returns the value of the selections made in the select boxes. 
It just looks like this: 

const targetValue = (i) => {
    return(
      i.currentTarget.value
    )} 

Couple of questions:

Where in the app should I put this function? 
Right now it is just in app.js (though it has nothing to do with it) and is passed down as props to Select (where it is called). 

How do I have this function return two separate values (one for the room select and one for the device) without repeating my code? Right now I've just called the function within each select onChange. Will this automatically return two values once both have selections made?

Forgive my not writing MD, haven't had a chance to look at it yet.

**Comment by jwhittle933** [comment]
First markdown tip: using triple back-ticks around your text to format your code. 

To record the value of a selection, you need to add an change listener to the select, i.e., 

``` 
onChange = { () => this.targetValue(e) }
```
This will have to either be in the component that contains the select, or you'll have to pass the function down from the parent.

**Comment by jwhittle933** [comment]
You'll need to store the resulting value in state.

**Comment by jwosborn** [comment]
Thanks for the tip. 

So you think I should just write that function directly in the select element? What is that value then stored in? 

right now it's like this: 
```<select className="Device-list" onChange={targetValue}>```

Should I have that targetValue function inside the Select component?

**Comment by jwhittle933** [comment]
You would declare the function in the component where the value needs to be stored in state. Then either call it in that component or pass it to the calling component. The way you call the method will change based on where you declare it. If its in called in the same component as declaration:
```
<select className="Device-list" onChange={this.targetValue}>
```
The ```this``` keyword is necessary in this case. If you pass it in via props, you can destruction, i.e., ```({targetValue})``` and then use it in the component, otherwise you have to call ```this.props.targetValue```.

**Comment by jwosborn** [comment]
Right. That makes sense. So probably declare the function in Select and store the value in it's state. I'll have to figure out how to store it. Let me bang my head for a while.  Thanks for the clarification on "this." believe it or not Guil did a great job on explaining that one.
