### ISSUE TITLE
Bash Profile 

### ISSUE THREAD

**Issue by jwhittle933** [jwosborn/Adapter-app#28]
# Yarn Install 
* go [here](https://yarnpkg.com/lang/en/docs/install/#mac-stable)

**Comment by jwhittle933** [comment]
You'll need to run `nano ~/.bashrc` or `nano ~/.bash_profile`. In this file, you'll add something like this `export PATH="$PATH:/opt/yarn-[version]/bin"`.

**Comment by jwhittle933** [comment]
Or, you could go ahead and download iTerm2, and then [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) and follow the install instructions. After this, your terminal will always load up with a single file, `.zshrc`, found at `~/.zshrc`. This is where you apply commands to your PATH variable that loads up with each terminal window.

**Comment by jwhittle933** [comment]
Or, just forget all this `yarn` stuff and use `npm`

**Comment by jwosborn** [comment]
npm doesn't seem to want to spool up the API.

**Comment by jwhittle933** [comment]
`export PATH=~/.yarn/bin:$PATH`
