### ISSUE TITLE
Select State pass to Negative component

### ISSUE THREAD

**Issue by jwosborn** [jwosborn/Adapter-app#6]
### Trying to think how to get "deviceTarget" which is in the Select component's state to the Negative component so it can access the appropriate adapter information from Devicelist. The components are siblings with the common parent App. 

* I could rewrite all the logic to have deviceTarget held in the App state and passed down as props to both Select and Negative but I need the Select component to be able to change it (callback) and the Negative component to just read it. 

* Would it be okay to push this up to App state and pass it back down?

* All the solutions I've found on stack and such involve redux, which I'm not using yet. Wanna get it done in vanilla (and i know it's possible) so I'm super comfortable passing this info back and forth. going forward.

**Comment by jwhittle933** [comment]
Pull and spinning up now...

**Comment by jwhittle933** [comment]
As it stands, I would create a state property on App.js, and write a method that you can pass down to Select, call, and set the App.js state. Then you can wire up Negative to simply receive the new App.js state as a prop.

**Comment by jwhittle933** [comment]
Keeping state in child components gets stringy, so it's better to "lift" your state to the parent.

**Comment by jwosborn** [comment]
My thoughts exactly. Requires nearly a full rewrite but will be worth it to have all the data passed down well and easily in the end. Getting to work on it this afternoon. 

Thanks for taking a look!
